#!/bin/sh

PORT="$(arduino-uart-dev)"

if [ -z "$PORT" ]; then
#    echo "UART Bridge not detected. Check connection."
    PORT="UART_NOT_FOUND"
else
    stty -F $PORT hupcl
fi

/usr/bin/avrdude -P $PORT $@
